export enum Icons {
  ARROW_DOWN = 'ARROW_DOWN',
  ARROW_LEFT_BACK = 'ARROW_LEFT_BACK',
  ARROW_RIGHT_RECIVED = 'ARROW_RIGHT_RECIVED',
  ARROW_RIGHT_SENT = 'ARROW_RIGHT_SENT',
  BUY = 'BUY',
  ELIPSE_PROFILE = 'ELIPSE_PROFILE',
  SETTINGS = 'SETTINGS',
  SWAP = 'SWAP',
  WALLET = 'WALLET',
}
